
    <!-- Define la codificación de caracteres -->
    <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
    <!-- Define el autor del documento -->
    <meta name="author" content="Carlos Prieto Parejo" />
    <!-- Define el programa con el que se ha generado el documento -->
    <meta name="generator" content="IntelliJ" />
    <!-- Define el copyright del documento -->
    <meta name="copyright" content="Boxing Gym Manager" />
    <!-- Define el comportamiento de los buscadores -->
    <meta name="robots" content="index, follow" />
    <!-- Define las palabras claves del contenido del documento -->
    <meta name="keywords" content="Gestion Boxeo" />
    <!-- Define una breve descripción del sitio -->
    <meta name="description" content="Gestion Gimnasio Boxeo" />

